### ISSUE TITLE
Peer to Peer Code Review: Module 2 Week 1 (refactor to use JavaScript classes)

### ISSUE THREAD

**Issue by DebbyMiressa** [kal2944/Awesome-books#3]
Hi @kal2944 👋 

<img src="https://media0.giphy.com/media/czubJ08i7deuKGJE9A/giphy.gif"/>

The project is almost complete now, great job!! But there are a few things to consider in order to make your project even more similar to the wireframe design.
1) The 'remove' buttons don't have a shadow cast as shown in the wireframe design.
2) The font and overall design must match the wireframe design given.

Again, Great Job🥇 for your amazing work!
Debby

**Comment by kal2944** [comment]
well, Noted! thank you so much!
